### ISSUE TITLE
[Feature Request] Add Eclipse support

### ISSUE THREAD

**Issue by gkeep** [WDKFernando/WAVE#1]
Basically, title. 

There is [nocturnal](https://github.com/Samgisaninja/nocturnal/), which is a CC module for Eclipse. This could be a start.

**Comment by WDKFernando** [comment]
Dune actually already toggles Eclipse by itself

**Comment by gkeep** [comment]
True, but Dune requires a respring to enable/disable Eclipse, while nocturnal does not.

**Comment by WDKFernando** [comment]
I will have at look it and see what I can do

**Comment by gkeep** [comment]
I was partially wrong. Some parts of Eclipse (like launch screens and alerts) require a respring, while in-app dark mode doesn't. So, in my opinion, the best of both worlds would be killing apps with Eclipse enabled.

I am looking into this myself, but as I've got no experience with Obj-C I cannot promise anything.

**Comment by gkeep** [comment]
Managed to do it. I will create a Pull Request shortly.

**Comment by WDKFernando** [comment]
thanks for helping - I will still have to make some changes of cosmetic nature before I upload it to Packix which might take some time since I am quiet busy at the moment

**Comment by gkeep** [comment]
Sure. Meanwhile, I'm going to create a separate issue about bubbles and BetterSettings support.
