### ISSUE TITLE
[WIP] BetterSettings and bubbles support

### ISSUE THREAD

**Issue by gkeep** [WDKFernando/WAVE#3]
This is everything I have found out so far about those tweaks.
### bubbles:
1. Has a Boolean switch in plist (`kEnabled` in com.creaturecoding.bubbles.plist).
2. Has integration with Noctis (Noctis integration to WAVE is unlikely (see https://github.com/Skittyblock/Dune/issues/17)).
3. Has three modes: Light (`1`), Dark (`0`) and Black (`2`). Toggle `kSchemeMode` in plist.
4. After switching modes or toggling bubbles Messages app has to restart. There is no way around that.

### BetterSettings:
1. Does not have a switch in plist (com.midnightchips.bettersettings.plist).
2. Has 5 presets, but there is no switch for them in plist.
3. Has backups with custom settings (possible to create a backup with mode colors and use that).
4. Settings app also has to be restarted after toggling.

**Comment by gkeep** [comment]
I am almost done with bubbles. Hopefully, will create PR today.

**Comment by WDKFernando** [comment]
I just saw that I apparently deleted your makefile in your fork, OwO, I'm so sorry, I didn't know that I was this powerful. 
(Btw I'm also new to using GitHub as a Git repo owner and should really learn how to use GitHub properly)

**Comment by gkeep** [comment]
No problem, I still had it on my PC. Plus, now I know that there is a `.theosrc` global config in home directory. I just set my stuff there now.

**Comment by gkeep** [comment]
There is a folder in `/var/mobile/Library/Preferences/` called `BetterSettings` with an empty file `preset`. It has no value in it nor does it change.

I'm really not sure how can we control BetterSettings. Of course, we can change all **13** values in plist according to presets, but that sounds more like a workaround than a solution.

**Comment by WDKFernando** [comment]
Here is the source code from midnightchip for [BetterSettings](https://github.com/midnightchip/BetterSettings). I personally will take a look at this next week, but I guess our solution is somewhere in the prefs more exact the backup and restore section.

**Comment by gkeep** [comment]
After a very quick look, I have found that there are really useful files in `/Library/PreferenceBundles/BetterSettings.bundle/`. For example, `Presets.plist`! With values of each preset. So there *must* be a switch somewhere. I'll keep digging around.

**Comment by gkeep** [comment]
There is no switch, sadly. It changes values according to the preset [here](https://github.com/midnightchip/BetterSettings/blob/d861c47bfc36372e3aa3557230d17fd5ae092c2a/bettersettings/BSPPreferenceController.m). We might as well just change values.

**Comment by gkeep** [comment]
Backend is done! I decided to just write preset's values the way BetterSettings does.

**Comment by WDKFernando** [comment]
I'll try adding it officially to master and the repo this weekend. You have done a great job and made a huge impact on this project WAVE. Thanks for all your hard work on WAVE.

**Comment by gkeep** [comment]
Pull request should've closed the issue automatically. Since everything is implemented, closing the issue.
