### ISSUE TITLE
[BUG] Settings close when WAVE's settings change while Eclipse quitting enabled

### ISSUE THREAD

**Issue by gkeep** [WDKFernando/WAVE#5]
**Steps to reproduce:**
1. Enable 'Quit all running apps' (it will close here too, for some reason)
2. Try to change any option in Ultrasound/PencilChargingIndicator

[Video representation](https://i.imgur.com/PVba9sY.mp4)

**Comment by WDKFernando** [comment]
I know why, I designed the settings to instantly apply the user prefs so the user doesn't have to toggle Dune manually by himself to apply.
So basically changing the prefs is the same as toggling Dune.
And now if you have "quit all Apps through Eclipse" enabled it will also apply that again.
I'll be able to fix this bug next weekend.

**Comment by gkeep** [comment]
Great. But I don't think current implementation is good enough. I think that it should kill *only* apps with Eclipse enabled, not all apps.

After I'm done with BetterSettings (I think I'll be done in the next few days), I'll try to rework that feature.

**Comment by WDKFernando** [comment]
The bug you found has now been fixed.
